clock_speed: 30.0
size: Medium

sizes:
  Large:
    proportion: 0.6
    bodies_of_water: 2
    water_body_size: Large
    num_plants: 160
    num_deer: 120
    num_wolfs: 12

  Medium:
    proportion: 1.0
    bodies_of_water: 2
    water_body_size: Medium
    num_plants: 80
    num_deer: 60
    num_wolfs: 10

  Small:
    proportion: 1.75
    bodies_of_water: 2
    water_body_size: Small
    num_plants: 40
    num_deer: 30
    num_wolfs: 5

  Custom:
    proportion: 0.6
    bodies_of_water: 1
    water_body_size: Medium
    num_plants: 50
    num_deer: 40
    num_wolfs: 8